apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-dm
  template:
    metadata:
      labels:
        app: server-dm
    spec:
      containers:
      - name: server-dm
        image: "registry.cn-chengdu.aliyuncs.com/work-daocker/daocker-server:v1.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-dm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort