apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-dm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-dm
  template:
    metadata:
      labels:
        app: ui-dm
    spec:
      containers:
      - name: ui-dm
        image: "registry.cn-chengdu.aliyuncs.com/work-daocker/daocker-ui:1.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-dm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort