[server]
addr = "0.0.0.0"
port = 4444

[datasource]
url = "sh-cynosdbmysql-grp-09nvk3xa.sql.tencentcdb.com:22763/daocker_db?characterEncoding=utf-8"
username = "daocker"
password = "daocker123@wpan"

[token]
secret_key = "wpan@tecwds"
expire = 64000