version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: 'daocker-server'
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    